// @vitest-environment node
import { describe, expect, it } from 'vitest';
import { validateCardDrafts } from './card-authoring';

describe('validateCardDrafts', () => {
	it('previews every distinct cloze ordinal', () => {
		const [result] = validateCardDrafts([
			{
				card_type: 'cloze',
				fields: [{ name: 'Text', value: '{{c1::Alpha}} and {{c2::Beta}} and {{c1::Gamma}}' }]
			}
		]);
		expect(result.valid).toBe(true);
		expect(result.previews.map((preview) => preview.ordinal)).toEqual([0, 1]);
	});

	it('rejects malformed drafts before any write occurs', () => {
		const [result] = validateCardDrafts([
			{
				card_type: 'cloze',
				fields: [
					{ name: 'Text', value: 'No cloze here' },
					{ name: 'text', value: '' }
				]
			}
		]);
		expect(result.valid).toBe(false);
		expect(result.errors).toEqual(
			expect.arrayContaining(['Duplicate field name: text', 'Cloze notes need at least one {{c1::answer}} deletion.'])
		);
	});

	it('bounds the number of cards generated by one cloze note', () => {
		const deletions = Array.from({ length: 21 }, (_, index) => `{{c${index + 1}::value}}`).join(' ');
		const [result] = validateCardDrafts([
			{ card_type: 'cloze', fields: [{ name: 'Text', value: deletions }] }
		]);
		expect(result.valid).toBe(false);
		expect(result.errors).toContain('A note can create at most 20 cloze cards.');
	});
});
