/// <reference lib="webworker" />

declare let self: ServiceWorkerGlobalScope;

import { build, files, version } from '$service-worker';

const CACHE_NAME = `ankitalk-${version}`;

// Assets generated by the build process + static files
const ASSETS = new Set([...build, ...files]);

self.addEventListener('install', (event) => {
	event.waitUntil(
		caches
			.open(CACHE_NAME)
			.then((cache) => cache.addAll([...ASSETS]))
			.then(() => self.skipWaiting())
	);
});

self.addEventListener('activate', (event) => {
	event.waitUntil(
		caches.keys().then(async (keys) => {
			for (const key of keys) {
				if (key !== CACHE_NAME) {
					await caches.delete(key);
				}
			}
			await self.clients.claim();
		})
	);
});

self.addEventListener('fetch', (event) => {
	const url = new URL(event.request.url);

	// Skip API routes — always network
	if (url.pathname.startsWith('/api/')) return;

	// Cache-first for known static assets only
	if (ASSETS.has(url.pathname)) {
		event.respondWith(
			caches.match(event.request).then((cached) => cached ?? fetch(event.request))
		);
		return;
	}

	// Network-only for page navigations — never serve stale HTML
	// This prevents hydration mismatches after deploys
	if (event.request.mode === 'navigate') {
		event.respondWith(
			fetch(event.request).catch(
				() =>
					caches
						.match(event.request)
						.then((cached) => cached ?? new Response('Offline', { status: 503 }))
			)
		);
		return;
	}
});
